import React from "react";
import LoggedClassesOverview from "../LoggedClassesOverview/LoggedClassesOverview";

const Grades = () => {
	const classLogs = [
		{
			date: "2024-11-01",
			period: "1st Period",
			lectureTitle: "Introduction to Algebra",
			sequence: "1",
			attendance: { present: 28, total: 30, absent: 2 },
			absentStudents: ["John Doe", "Jane Smith"],
		},
		{
			date: "2024-11-02",
			period: "2nd Period",
			lectureTitle: "Linear Equations",
			sequence: "2",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
		{
			date: "2024-11-03",
			period: "3rd Period",
			lectureTitle: "Quadratic Equations",
			sequence: "3",
			attendance: { present: 29, total: 30, absent: 1 },
			absentStudents: ["Alice Brown"],
		},
		{
			date: "2024-11-04",
			period: "1st Period",
			lectureTitle: "Polynomials",
			sequence: "4",
			attendance: { present: 27, total: 30, absent: 3 },
			absentStudents: ["Sam Wilson", "Chris Evans", "Natalie Portman"],
		},
		{
			date: "2024-11-05",
			period: "2nd Period",
			lectureTitle: "Functions and Graphs",
			sequence: "5",
			attendance: { present: 28, total: 30, absent: 2 },
			absentStudents: ["Robert Downey", "Scarlett Johansson"],
		},
		{
			date: "2024-11-06",
			period: "3rd Period",
			lectureTitle: "Exponential Functions",
			sequence: "6",
			attendance: { present: 26, total: 30, absent: 4 },
			absentStudents: [
				"Mark Ruffalo",
				"Chris Hemsworth",
				"Tom Hiddleston",
				"Benedict Cumberbatch",
			],
		},
		{
			date: "2024-11-07",
			period: "1st Period",
			lectureTitle: "Logarithmic Functions",
			sequence: "7",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
		{
			date: "2024-11-08",
			period: "2nd Period",
			lectureTitle: "Sequences and Series",
			sequence: "8",
			attendance: { present: 29, total: 30, absent: 1 },
			absentStudents: ["Chris Pratt"],
		},
		{
			date: "2024-11-09",
			period: "3rd Period",
			lectureTitle: "Probability",
			sequence: "9",
			attendance: { present: 28, total: 30, absent: 2 },
			absentStudents: ["Paul Rudd", "Jeremy Renner"],
		},
		{
			date: "2024-11-10",
			period: "1st Period",
			lectureTitle: "Statistics",
			sequence: "10",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
		{
			date: "2024-11-11",
			period: "2nd Period",
			lectureTitle: "Geometry Basics",
			sequence: "11",
			attendance: { present: 29, total: 30, absent: 1 },
			absentStudents: ["Michael B. Jordan"],
		},
		{
			date: "2024-11-12",
			period: "3rd Period",
			lectureTitle: "Triangles and Circles",
			sequence: "12",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
		{
			date: "2024-11-13",
			period: "1st Period",
			lectureTitle: "Trigonometry Introduction",
			sequence: "13",
			attendance: { present: 27, total: 30, absent: 3 },
			absentStudents: ["Emma Stone", "Ryan Gosling", "Emma Watson"],
		},
		{
			date: "2024-11-14",
			period: "2nd Period",
			lectureTitle: "Sine and Cosine",
			sequence: "14",
			attendance: { present: 28, total: 30, absent: 2 },
			absentStudents: ["Chris Pine", "Zoe Saldana"],
		},
		{
			date: "2024-11-15",
			period: "3rd Period",
			lectureTitle: "Tangent and Cotangent",
			sequence: "15",
			attendance: { present: 29, total: 30, absent: 1 },
			absentStudents: ["Tom Cruise"],
		},
		{
			date: "2024-11-16",
			period: "1st Period",
			lectureTitle: "Logarithms in Depth",
			sequence: "16",
			attendance: { present: 28, total: 30, absent: 2 },
			absentStudents: ["Dwayne Johnson", "Kevin Hart"],
		},
		{
			date: "2024-11-17",
			period: "2nd Period",
			lectureTitle: "Introduction to Calculus",
			sequence: "17",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
		{
			date: "2024-11-18",
			period: "3rd Period",
			lectureTitle: "Limits and Continuity",
			sequence: "18",
			attendance: { present: 29, total: 30, absent: 1 },
			absentStudents: ["Will Smith"],
		},
		{
			date: "2024-11-19",
			period: "1st Period",
			lectureTitle: "Derivatives",
			sequence: "19",
			attendance: { present: 27, total: 30, absent: 3 },
			absentStudents: ["Brad Pitt", "Leonardo DiCaprio", "Johnny Depp"],
		},
		{
			date: "2024-11-20",
			period: "2nd Period",
			lectureTitle: "Integrals",
			sequence: "20",
			attendance: { present: 28, total: 30, absent: 2 },
			absentStudents: ["Angelina Jolie", "Jennifer Lawrence"],
		},
		{
			date: "2024-11-21",
			period: "3rd Period",
			lectureTitle: "Definite and Indefinite Integrals",
			sequence: "21",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
		{
			date: "2024-11-22",
			period: "1st Period",
			lectureTitle: "Introduction to Differential Equations",
			sequence: "22",
			attendance: { present: 29, total: 30, absent: 1 },
			absentStudents: ["Hugh Jackman"],
		},
		{
			date: "2024-11-23",
			period: "2nd Period",
			lectureTitle: "Partial Differential Equations",
			sequence: "23",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
		{
			date: "2024-11-24",
			period: "3rd Period",
			lectureTitle: "Fourier Series",
			sequence: "24",
			attendance: { present: 28, total: 30, absent: 2 },
			absentStudents: ["Matthew McConaughey", "Anne Hathaway"],
		},
		{
			date: "2024-11-25",
			period: "1st Period",
			lectureTitle: "Laplace Transforms",
			sequence: "25",
			attendance: { present: 29, total: 30, absent: 1 },
			absentStudents: ["Morgan Freeman"],
		},
		{
			date: "2024-11-26",
			period: "2nd Period",
			lectureTitle: "Vector Calculus",
			sequence: "26",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
		{
			date: "2024-11-27",
			period: "3rd Period",
			lectureTitle: "Eigenvalues and Eigenvectors",
			sequence: "27",
			attendance: { present: 28, total: 30, absent: 2 },
			absentStudents: ["Tom Hanks", "Julia Roberts"],
		},
		{
			date: "2024-11-28",
			period: "1st Period",
			lectureTitle: "Linear Transformations",
			sequence: "28",
			attendance: { present: 29, total: 30, absent: 1 },
			absentStudents: ["Halle Berry"],
		},
		{
			date: "2024-11-29",
			period: "2nd Period",
			lectureTitle: "Probability Distributions",
			sequence: "29",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
		{
			date: "2024-11-30",
			period: "3rd Period",
			lectureTitle: "Hypothesis Testing",
			sequence: "30",
			attendance: { present: 30, total: 30, absent: 0 },
			absentStudents: [],
		},
	];

	return (
		<div>
			<LoggedClassesOverview initialLogs={classLogs} />
		</div>
	);
};

export default Grades;
